### ISSUE TITLE
Notes Button misplaced

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#274] opened 2017-01-18 16:50 UTC
Notes button sitting in funny place. Will only place correctly if the window is reduced to minimum width 
![screen shot 2017-01-18 at 10 49 17 am](https://cloud.githubusercontent.com/assets/17204541/22073777/deda9912-dd6b-11e6-9d47-9d1a7be36b6d.png)

**Comment by thehabes** [comment] 2017-01-20 20:52
seems to be specific to the iMac.

**Comment by Domhnall101** [comment] 2017-01-31 16:24
this is still not working right in RTL - check with Patric k for his resolution to it
![screen shot 2017-01-31 at 10 23 27 am](https://cloud.githubusercontent.com/assets/17204541/22473727/63719b5c-e79f-11e6-9fa9-4829bfbfc865.png)

**Comment by thehabes** [comment] 2017-01-31 16:30
This is a duplicate of #331.  Please assign to Patrick, I put clear-right on it for the right side like he put clear-left on it for the left side, but it didn't work.  He seems to know exactly what to do for this one.

**Closed** 2017-02-27 16:40 UTC
Labels: bug, duplicate, RTL, transcription interface
