### ISSUE TITLE
Peculiar moving white bar/gap when splitting screen

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#140] opened 2016-12-05 19:57 UTC

**Comment by thehabes** [comment] 2016-12-05 20:19
From ticket duplicate:

The positioning built into the UI causes a variable sized white bar in between the split screen section and transcription area section. It changes width as you change the width of your browser.

Connected to that same issue, if you change the width of this screen and cause the area to wrap underneath, resizing the transcription by clicking and dragging fixes the issue because the math takes into account the area of the size available to fit the image into it, stopping the wrap. I believe these are caused by the same problem.

The resizing math attached the resizing by clicking and dragging to change the size of the transcription area also needs to be applied on screen resize to keep everything consistent and have it function exactly right, but it works the way it is for now.

**Comment by thehabes** [comment] 2016-12-05 20:47
Make sure this fix will work with #145

**Comment by thehabes** [comment] 2016-12-09 21:43
This is very connected to #147.  I happened to "fix" it while I was playing around with this ticket.

**Comment by thehabes** [comment] 2016-12-12 22:26
This is fixed with #147, I am going to put some finishing touches on these and close them tonight/tomorrow morning.

**Comment by cubap** [comment] 2016-12-13 15:53
This had been assigned to me, but I don't want to overlap your work. Is it finished?

**Comment by thehabes** [comment] 2016-12-13 16:04
Not yet, but I am working on it

**Comment by cubap** [comment] 2016-12-13 16:04
Okay, I'll move to the next milestone

**Comment by thehabes** [comment] 2016-12-14 17:56
This is happening because of #178.  When that is fixed, this will be fixed.

**Comment by thehabes** [comment] 2016-12-16 21:18
So far, testing has shown this is fixed with #178.  Running final tests...

**Closed** 2016-12-16 22:32 UTC
Labels: bug
