### ISSUE TITLE
issue reported by user  - shift number commands in classic broken + speed to load issue in 2.8

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#479] opened 2017-05-24 17:24 UTC
“Hi everyone. I'm using T-Pen at the University of Bern, Switzerland, for a research project.
Version 2.8 is still very slow and not usable for us.
Now the problem is: The shortkeys (Characters and XML tags) in the classic version do not work any more. I press e.g.  CTRL + 1, but nothing happens
Is there any way to fix this?
Michael”
 

My project ID is 5258, called “Einsiedeln, KAE A.HB.4_d.”, it’s part of a large research project, I’m only one of several transcribers.
However, v2.8 is still very slow. I just tested it (after deleting Cache and reloading, when the bug was already fixed and worked). The v2.8 took more than 2 minutes to load my project. The Classic version only needs about 3 seconds to load the project.
 
So, thank you for fixing the bug, but v2.8 is still way too slow to work fluently. (However, Classic version works just fine for me, now that I can use the shortkeys again).

**Comment by thehabes** [comment] 2017-05-24 18:53
SHIFT + # commands are confirmed fixed by user.

We have a fix for the speed issue that we will upload with Friday's maintenance window.

**Comment by thehabes** [comment] 2017-06-05 14:45
The issue causing the extreme lag was one line in the Java back end that took the manifest string built by the JSONExporter and parsed it into a JSONObject, which we still aren't exactly sure why but that's not important.

What is important is that it was being parsed twice.  I specifically parsed the manifest object, and then parsed the project object (which the manifest is a part of) at then end as well.

The goofy part is that this project object that contains the manifest had no lag time in parsing, so by simply commenting out the initial manifest parse action, we completely eliminated the lag, although it left us puzzled to the cause.

This has been deployed, tested and confirmed fixed and we documented the anomaly in the code.

**Comment by thehabes** [comment] 2017-06-05 14:52
If you would like to test the fix yourself you can do so at this link http://t-pen.org/TPEN/transcription.html?projectID=5258

**Comment by Domhnall101** [comment] 2017-06-05 15:06
T_pen is down. Opening this link in Chrome took it out

On Mon, Jun 5, 2017 at 9:52 AM, Bryan Haberberger <notifications@github.com>
wrote:

> If you would like to test the fix yourself you can do so at this link
> http://t-pen.org/TPEN/transcription.html?projectID=5258
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__t-2Dpen.org_TPEN_transcription.html-3FprojectID-3D5258&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=L-Fy3Uv74J3fuepDaLkX_EDB8KNOQW_syeRx9t0uFGM&s=KoeZvh76h-wx_zc5R_ALLGbWYaDAbDo4J73LICj7JNg&e=>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_479-23issuecomment-2D306208134&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=L-Fy3Uv74J3fuepDaLkX_EDB8KNOQW_syeRx9t0uFGM&s=eT5mKDELwjIQGtlRAG0-oDHERQgKFdjHvSXsbH5c6u4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQaFPUH-2DsYjfn4tAcrcPPm3ZvzXmEVLuks5sBBY4gaJpZM4NlbFB&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=L-Fy3Uv74J3fuepDaLkX_EDB8KNOQW_syeRx9t0uFGM&s=YTFycVVEZ5ytgWoKgowm0fDioq3zp6SXzt8woFyQGxc&e=>
> .
>



-- 
Donal Hegarty
Project Manager/UX Designer
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314 9774248

**Closed** 2018-07-27 13:04 UTC
